# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Flight_count.py
# Created on: 2018-09-13 10:30:14.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Flight_count <Region> <data_shp> 
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("C:/Users/Hong/Documents/ArcGIS/ADS-B/ADS-B.tbx")

# Script arguments
Region = arcpy.GetParameterAsText(0)
if Region == '#' or not Region:
    Region = "SHANDONG" # provide a default value if unspecified

data_shp = arcpy.GetParameterAsText(1)
if data_shp == '#' or not data_shp:
    data_shp = "C:\\Users\\Hong\\Documents\\ArcGIS\\ADS-B\\1536730700.shp" # provide a default value if unspecified

# Local variables:
v1536229130_Layer = "1536730700_Layer1"
v1536229130_Layer__3_ = v1536229130_Layer
bou2_4p = "bou2_4p"
region_shp = bou2_4p
expression__2_ = Region
inter1 = "C:\\Users\\Hong\\Documents\\ArcGIS\\ADS-B\\ADS-B.gdb\\inter1"
flight_num = "C:\\Users\\Hong\\Documents\\ArcGIS\\ADS-B\\ADS-B.gdb\\flight_num"
flight_num__4_ = flight_num
inter_time = "C:\\Users\\Hong\\Documents\\ArcGIS\\ADS-B\\ADS-B.gdb\\inter_time"
flight_num__6_ = flight_num__4_
flight_num__3_ = flight_num__6_
flight_num__5_ = flight_num__3_
bou2_4p_Select = "C:\\Users\\Hong\\Documents\\ArcGIS\\ADS-B\\ADS-B.gdb\\bou2_4p_Select"
flight_num__10_ = flight_num__5_
flight_num__2_ = flight_num__10_
ATF_COUNT__2_ = flight_num__2_
ATF_COUNT = "C:\\Users\\Hong\\Documents\\ArcGIS\\ADS-B\\ADS-B.gdb\\ATF_COUNT"

# Process: Make Feature Layer (2)
arcpy.MakeFeatureLayer_management(data_shp, v1536229130_Layer, "", "", "FID FID VISIBLE NONE;Shape Shape VISIBLE NONE;callsign callsign VISIBLE NONE;lon lon VISIBLE NONE;lat lat VISIBLE NONE;geoaltitud geoaltitud VISIBLE NONE;heading heading VISIBLE NONE;icao24 icao24 VISIBLE NONE;time time VISIBLE NONE")

# Process: Expression
arcpy.gp.toolbox = "C:/Users/Hong/Documents/ArcGIS/ADS-B/ADS-B.tbx";
# Warning: the toolbox C:/Users/Hong/Documents/ArcGIS/ADS-B/ADS-B.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.expression(...) with arcpy.expression_ALIAS(...)
arcpy.gp.expression(Region)

# Process: Select Layer By Attribute
arcpy.SelectLayerByAttribute_management(bou2_4p, "NEW_SELECTION", expression__2_)

# Process: Select Layer By Location
arcpy.SelectLayerByLocation_management(v1536229130_Layer, "WITHIN", region_shp, "", "NEW_SELECTION", "NOT_INVERT")

# Process: Frequency
arcpy.Frequency_analysis(v1536229130_Layer__3_, inter1, "callsign", "")

# Process: Summary Statistics
arcpy.Statistics_analysis(inter1, flight_num, "callsign COUNT", "")

# Process: Summary Statistics (2)
arcpy.Statistics_analysis(v1536229130_Layer, inter_time, "time MAX;time MIN", "")

# Process: Join Field
arcpy.JoinField_management(flight_num, "OBJECTID", inter_time, "OBJECTID", "OBJECTID;FREQUENCY;MAX_time;MIN_time")

# Process: Alter Field
arcpy.AlterField_management(flight_num__4_, "FREQUENCY_1", "COUNT_data", "", "", "4", "NON_NULLABLE", "true")

# Process: Delete Field
arcpy.DeleteField_management(flight_num__6_, "FREQUENCY")

# Process: Select
arcpy.Select_analysis(bou2_4p, bou2_4p_Select, expression__2_)

# Process: Join Field (2)
arcpy.JoinField_management(flight_num__3_, "OBJECTID", bou2_4p_Select, "OBJECTID", "PROVINCE")

# Process: Convert Time Field
arcpy.ConvertTimeField_management(flight_num__5_, "MAX_time", "yyyy-MM-dd HH:mm:ss;1028;;", "end_time", "DATE", "'Not Used'")

# Process: Convert Time Field (2)
arcpy.ConvertTimeField_management(flight_num__10_, "MIN_time", "yyyy-MM-dd HH:mm:ss;1028;;", "start_time", "DATE", "'Not Used'")

# Process: Append
arcpy.Append_management("C:\\Users\\Hong\\Documents\\ArcGIS\\ADS-B\\ADS-B.gdb\\flight_num", ATF_COUNT, "NO_TEST", "FLIGHT \"FLIGHT\" true true false 2 Short 0 0 ,First,#,C:\\Users\\Hong\\Documents\\ArcGIS\\ADS-B\\ADS-B.gdb\\flight_num,COUNT_callsign,-1,-1;DATA \"DATA\" true true false 2 Short 0 0 ,First,#,C:\\Users\\Hong\\Documents\\ArcGIS\\ADS-B\\ADS-B.gdb\\flight_num,COUNT_data,-1,-1;START_TIME \"START_TIME\" true true false 50 Text 0 0 ,First,#,C:\\Users\\Hong\\Documents\\ArcGIS\\ADS-B\\ADS-B.gdb\\flight_num,start_time,-1,-1;END_TIME \"END_TIME\" true true false 50 Text 0 0 ,First,#,C:\\Users\\Hong\\Documents\\ArcGIS\\ADS-B\\ADS-B.gdb\\flight_num,end_time,-1,-1;PROVINCE \"PROVINCE\" true true false 50 Text 0 0 ,First,#,C:\\Users\\Hong\\Documents\\ArcGIS\\ADS-B\\ADS-B.gdb\\flight_num,PROVINCE,-1,-1", "")

