# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Tracking_Layer.py
# Created on: 2018-09-13 10:29:20.00000
#   (generated by ArcGIS/ModelBuilder)
# Modified by Yvonne YU
# Usage: Tracking_Layer <v1536730700_shp> <Time_Field> <Track_ID_Field> <Tracking_Layer> 
# Description: 
# Create a tracking layer depends on the existed shp file
# Aeronautique symbology will be applied
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

#path
workspace = "C:\\Users\\Hong\\Documents\\ArcGIS\\ADS-B"
csv_folder = "D:\\Thales\\ADS-B\\coordinate"

# Script arguments
shp = arcpy.GetParameterAsText(0)
if shp == '#' or not shp:
    shp = "C:\\Users\\Hong\\Documents\\ArcGIS\\ADS-B\\1536730700.shp" # provide a default value if unspecified

Time_Field = arcpy.GetParameterAsText(1)
if Time_Field == '#' or not Time_Field:
    Time_Field = "time" # provide a default value if unspecified

Track_ID_Field = arcpy.GetParameterAsText(2)
if Track_ID_Field == '#' or not Track_ID_Field:
    Track_ID_Field = "callsign" # provide a default value if unspecified

Tracking_Layer = arcpy.GetParameterAsText(3)
if Tracking_Layer == '#' or not Tracking_Layer:
    Tracking_Layer = "1536730700_Layer" # provide a default value if unspecified

# Local variables:
template_lyr = workspace+"\\template.lyr"
Layer1 = "1536730700_Layer"
csv = csv_folder+"\\1536719890.csv"
Layer = "1536719890_Layer"
ADS_B = workspace
ADS_B__2_ = ADS_B

# Process: Make Tracking Layer
arcpy.MakeTrackingLayer_ta(shp, Layer1, "NO_TIME_ZONE", "ADJUSTED_FOR_DST", "COPY_ALL_TO_MEMORY", Time_Field, "", "2052", "上午", "下午", Track_ID_Field)

# Process: Apply Symbology From Layer
arcpy.ApplySymbologyFromLayer_management(Layer1, template_lyr)

# Process: Make XY Event Layer
arcpy.MakeXYEventLayer_management("", "", "", Layer, "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8,98315284119522E-09;0,001;0,001;IsHighPrecision", "")

# Process: Feature Class To Shapefile (multiple)
arcpy.FeatureClassToShapefile_conversion("1536719890_Layer", ADS_B)

