# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Update_province.py
# Created on: 2018-09-13 10:29:46.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
bou2_4p_shp = "C:\\Users\\Hong\\Documents\\ArcGIS\\ADS-B\\省界\\bou2_4p.shp"
bou2_4p_shp__2_ = bou2_4p_shp
bou2_4p_Layer = "bou2_4p_Layer"
bou2_4p_Layer__3_ = bou2_4p_Layer
bou2_4p_Layer__2_ = bou2_4p_Layer__3_
省名_xlsx = "C:\\Users\\Hong\\Documents\\ArcGIS\\ADS-B\\省界\\省名.xlsx"
Output_Table = "C:\\Users\\Hong\\Documents\\ArcGIS\\ADS-B\\ADS-B.gdb\\省名_ExcelToTable"

# Process: Define Projection
arcpy.DefineProjection_management(bou2_4p_shp, "GEOGCS['WGS_1984_(Transit)',DATUM['World_Geodetic_System_1984_(Transit)',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]")

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(bou2_4p_shp__2_, bou2_4p_Layer, "", "", "FID FID VISIBLE NONE;Shape Shape VISIBLE NONE;AREA AREA VISIBLE NONE;PERIMETER PERIMETER VISIBLE NONE;BOU2_4M_ BOU2_4M_ VISIBLE NONE;BOU2_4M_ID BOU2_4M_ID VISIBLE NONE;ADCODE93 ADCODE93 VISIBLE NONE;ADCODE99 ADCODE99 VISIBLE NONE;PROVINCE PROVINCE VISIBLE NONE;PROVINCE_1 PROVINCE_1 VISIBLE NONE;PROVINCE_2 PROVINCE_2 VISIBLE NONE")

# Process: Delete Field
arcpy.DeleteField_management(bou2_4p_Layer, "PROVINCE")

# Process: Excel To Table
arcpy.ExcelToTable_conversion(省名_xlsx, Output_Table, "Sheet1")

# Process: Join Field (2)
arcpy.JoinField_management(bou2_4p_Layer__3_, "BOU2_4M_", Output_Table, "BOU2_4M", "PROVINCE")

